# Generated by Django 6.0 on 2026-10-03 15:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "magic_type",
                    models.CharField(
                        choices=[
                            ("FC", "Полный заклинатель"),
                            ("HC", "Полузаклинатель"),
                            ("TC", "Треть-заклинатель"),
                            ("NC", "Немагический класс"),
                        ],
                        default="NC",
                        max_length=2,
                        verbose_name="Магический тип",
                    ),
                ),
                (
                    "hit_die",
                    models.IntegerField(
                        choices=[
                            (2, "d2"),
                            (4, "d4"),
                            (6, "d6"),
                            (8, "d8"),
                            (10, "d10"),
                            (12, "d12"),
                            (20, "d20"),
                            (100, "d100"),
                        ],
                        default=8,
                        help_text="Кость хитов",
                        verbose_name="Кости хитов",
                    ),
                ),
                (
                    "spellcasting_ability",
                    models.CharField(
                        choices=[
                            ("STR", "Сила"),
                            ("DEX", "Ловкость"),
                            ("CON", "Телосложение"),
                            ("INT", "Интеллект"),
                            ("WIS", "Мудрость"),
                            ("CHA", "Харизма"),
                        ],
                        default="WIS",
                        help_text="Заклинательная характеристика",
                        max_length=3,
                        verbose_name="Заклинательная характеристика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
            },
        ),
        migrations.CreateModel(
            name="DamageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_magic",
                    models.BooleanField(default=True, verbose_name="Магический урон"),
                ),
            ],
            options={
                "verbose_name": "Тип урона",
                "verbose_name_plural": "Типы урона",
            },
        ),
        migrations.CreateModel(
            name="MagicSchool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=99, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "color",
                    models.CharField(
                        default="#3498db", max_length=7, verbose_name="Цвет школы магии"
                    ),
                ),
            ],
            options={
                "verbose_name": "Школа магии",
                "verbose_name_plural": "Школы магии",
            },
        ),
        migrations.CreateModel(
            name="MaterialComponent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.TextField(max_length=49, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание компонента"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Стоимость в ЗМ",
                        max_digits=7,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "is_consumable",
                    models.BooleanField(
                        default=False,
                        help_text="Расходуется ли компонент при касте заклинания",
                        verbose_name="Потребляемый",
                    ),
                ),
                (
                    "is_focus",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли фокусировкой для заклинания",
                        verbose_name="Фокус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материальный компонент",
                "verbose_name_plural": "Материальные компоненты",
            },
        ),
        migrations.CreateModel(
            name="SpellTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("time", models.CharField(max_length=49, verbose_name="Время")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Время накладывания заклинания",
                "verbose_name_plural": "Время накладывания заклинаний",
            },
        ),
        migrations.CreateModel(
            name="Effect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=49, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COND", "Состояние"),
                            ("CTRL", "Контроль"),
                            ("DEBF", "Ослабление"),
                            ("BUFF", "Усиление"),
                            ("UTIL", "Полезный эффект"),
                            ("MOVE", "Перемещение"),
                            ("TP", "Телепортация"),
                            ("HEAL", "Исцеление"),
                            ("DMG", "Урон"),
                            ("PROT", "Защита"),
                            ("TMUT", "Трансмутация"),
                        ],
                        max_length=4,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Время действия эффекта",
                        max_length=100,
                        verbose_name="Продолжительность",
                    ),
                ),
                (
                    "damage_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Тип урона при наличии",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="effects",
                        to="spells.damagetype",
                        verbose_name="Тип урона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эффект заклинания",
                "verbose_name_plural": "Эффекты заклинаний",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="Ник"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание персонажа",
                        verbose_name="Краткое описание персонажа",
                    ),
                ),
                (
                    "experience_points",
                    models.IntegerField(
                        default=0,
                        help_text="Опыт игрока (не персонажей) в годах",
                        verbose_name="Опыт игрока (не персонажа)",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Телеграмм id"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        null=True, upload_to="player_avatars/", verbose_name="Аватар"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Зарегистрировался",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Последний вход"
                    ),
                ),
                (
                    "favorite_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favored_by_players",
                        to="spells.characterclass",
                        verbose_name="Любимый класс",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "primary_class_level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Уровень основного класса",
                    ),
                ),
                (
                    "race",
                    models.CharField(blank=True, max_length=100, verbose_name="Раса"),
                ),
                (
                    "subrace",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Подраса"
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LG", "Законно-добрый"),
                            ("NG", "Нейтрально-добрый"),
                            ("CG", "Хаотично-добрый"),
                            ("LN", "Законно-нейтральный"),
                            ("TN", "Истинно-нейтральный"),
                            ("CN", "Хаотично-нейтральный"),
                            ("LE", "Законно-злой"),
                            ("NE", "Нейтрально-злой"),
                            ("CE", "Хаотично-злой"),
                        ],
                        max_length=2,
                        verbose_name="Мировоззрение",
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Предыстория"
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Сила",
                    ),
                ),
                (
                    "dexterity",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Ловкость",
                    ),
                ),
                (
                    "constitution",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Телосложение",
                    ),
                ),
                (
                    "intelligence",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Интеллект",
                    ),
                ),
                (
                    "wisdom",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Мудрость",
                    ),
                ),
                (
                    "charisma",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Харизма",
                    ),
                ),
                (
                    "max_hit_points",
                    models.IntegerField(
                        default=10, verbose_name="Макисмальное кол-во хитов"
                    ),
                ),
                (
                    "current_hit_points",
                    models.IntegerField(
                        default=10, verbose_name="Текущее кол-во хитов"
                    ),
                ),
                (
                    "temporary_hit_points",
                    models.IntegerField(
                        default=0, verbose_name="Временное кол-во хитов"
                    ),
                ),
                (
                    "armor_class",
                    models.IntegerField(default=10, verbose_name="Класс доспеха (КД)"),
                ),
                (
                    "initiative_bonus",
                    models.IntegerField(
                        default=0, verbose_name="Модификатор инициативы"
                    ),
                ),
                (
                    "speed",
                    models.IntegerField(
                        default=30,
                        help_text="Скорость в футах",
                        verbose_name="Скорость",
                    ),
                ),
                (
                    "proficiency_bonus",
                    models.IntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Бонус мастерства",
                    ),
                ),
                (
                    "spellcasting_ability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STR", "Сила"),
                            ("DEX", "Ловкость"),
                            ("CON", "Телосложение"),
                            ("INT", "Интеллект"),
                            ("WIS", "Мудрость"),
                            ("CHA", "Харизма"),
                        ],
                        help_text="Заклинательная характеристика",
                        max_length=3,
                        verbose_name="Характеристика",
                    ),
                ),
                (
                    "is_multiclass",
                    models.BooleanField(default=False, verbose_name="Мультикласс"),
                ),
                (
                    "second_class_level",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(19),
                        ],
                        verbose_name="Второй уровень класса",
                    ),
                ),
                (
                    "warlock_level",
                    models.IntegerField(
                        default=0,
                        help_text="Уровень колдуна (если мультикласс)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Уровень колдуна",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Любимый"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Могут ли другие игроки видеть",
                        verbose_name="Публичный",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создано"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="spells.characterclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "second_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_characters",
                        to="spells.characterclass",
                        verbose_name="Дополнительный класс",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="spells.player",
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонаж",
                "verbose_name_plural": "Персонажи",
                "ordering": ["-is_favorite", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "lv0"),
                            (1, "lv1"),
                            (2, "lv2"),
                            (3, "lv3"),
                            (4, "lv4"),
                            (5, "lv5"),
                            (6, "lv6"),
                            (7, "lv7"),
                            (8, "lv8"),
                            (9, "lv9"),
                        ],
                        default=0,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "verbal_component",
                    models.BooleanField(
                        default=False,
                        help_text="Вербальный компонент",
                        verbose_name="Вербальный компонент",
                    ),
                ),
                (
                    "somatic_component",
                    models.BooleanField(
                        default=False,
                        help_text="Соматический компонент",
                        verbose_name="Соматический компонент",
                    ),
                ),
                (
                    "range",
                    models.CharField(
                        blank=True,
                        help_text="Дистанция (по умолчанию в футах)",
                        max_length=100,
                        verbose_name="Дистанция",
                    ),
                ),
                (
                    "duration",
                    models.CharField(max_length=100, verbose_name="Длительность"),
                ),
                (
                    "concentration",
                    models.BooleanField(default=False, verbose_name="Концентрация"),
                ),
                ("ritual", models.BooleanField(default=False, verbose_name="Ритуал")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "higher_level",
                    models.TextField(
                        blank=True,
                        help_text="На более высоком уровне",
                        verbose_name="На более высоком уровне",
                    ),
                ),
                (
                    "attack_type",
                    models.CharField(
                        choices=[
                            ("ATTACK", "Бросок атаки"),
                            ("SAVE", "Спасбросок"),
                            ("AUTO", "Автоматическое"),
                            ("MIXED", "Комбинированное"),
                            ("NONE", "Нет броска"),
                        ],
                        default="NONE",
                        max_length=10,
                        verbose_name="Механика",
                    ),
                ),
                (
                    "saving_throw_ability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STR", "Сила"),
                            ("DEX", "Ловкость"),
                            ("CON", "Телосложение"),
                            ("INT", "Интеллект"),
                            ("WIS", "Мудрость"),
                            ("CHA", "Харизма"),
                        ],
                        help_text="Характеристика для спасброска (если требуется)",
                        max_length=3,
                        verbose_name="Характеристика для спасброска",
                    ),
                ),
                (
                    "source_book",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Источник"
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Страница источника"
                    ),
                ),
                (
                    "is_official",
                    models.BooleanField(default=True, verbose_name="Официальное"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создано"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aviable_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="aviable_spells",
                        to="spells.characterclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, добавивший заклинание",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_spells",
                        to="spells.player",
                        verbose_name="Пользователь, добавивший заклинание",
                    ),
                ),
                (
                    "effects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="spells",
                        to="spells.effect",
                        verbose_name="Эффект заклинания",
                    ),
                ),
                (
                    "material_components",
                    models.ManyToManyField(
                        to="spells.materialcomponent",
                        verbose_name="Материальный компонент",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spells.magicschool",
                        verbose_name="Школа магии",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spells.spelltime",
                        verbose_name="Время",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заклинание",
                "verbose_name_plural": "Заклинания",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Spellbook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Активен ли этот спеллбук",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Доступен ли для других игроков",
                        verbose_name="Публичный",
                    ),
                ),
                (
                    "max_spell_slots_1",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 1го уровня"
                    ),
                ),
                (
                    "max_spell_slots_2",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 2го уровня"
                    ),
                ),
                (
                    "max_spell_slots_3",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 3го уровня"
                    ),
                ),
                (
                    "max_spell_slots_4",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 4го уровня"
                    ),
                ),
                (
                    "max_spell_slots_5",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 5го уровня"
                    ),
                ),
                (
                    "max_spell_slots_6",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 6го уровня"
                    ),
                ),
                (
                    "max_spell_slots_7",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 7го уровня"
                    ),
                ),
                (
                    "max_spell_slots_8",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 8го уровня"
                    ),
                ),
                (
                    "max_spell_slots_9",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек 9го уровня"
                    ),
                ),
                (
                    "current_spell_slots_1",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 1го уровня"
                    ),
                ),
                (
                    "current_spell_slots_2",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 2го уровня"
                    ),
                ),
                (
                    "current_spell_slots_3",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 3го уровня"
                    ),
                ),
                (
                    "current_spell_slots_4",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 4го уровня"
                    ),
                ),
                (
                    "current_spell_slots_5",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 5го уровня"
                    ),
                ),
                (
                    "current_spell_slots_6",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 6го уровня"
                    ),
                ),
                (
                    "current_spell_slots_7",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 7го уровня"
                    ),
                ),
                (
                    "current_spell_slots_8",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 8го уровня"
                    ),
                ),
                (
                    "current_spell_slots_9",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек 9го уровня"
                    ),
                ),
                (
                    "warlock_slot_level",
                    models.IntegerField(
                        default=0, verbose_name="Уровень ячейки колдуна"
                    ),
                ),
                (
                    "warlock_max_slots",
                    models.IntegerField(
                        default=0, verbose_name="Максимальное кол-во ячеек колдуна"
                    ),
                ),
                (
                    "warlock_current_slots",
                    models.IntegerField(
                        default=0, verbose_name="Текущее кол-во ячеек колдуна"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний заход"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spellbooks",
                        to="spells.person",
                        verbose_name="Персонаж",
                    ),
                ),
                (
                    "spells",
                    models.ManyToManyField(
                        blank=True,
                        related_name="spellbooks",
                        to="spells.spell",
                        verbose_name="Заклинания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спеллбук",
                "verbose_name_plural": "Спеллбуки",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Subclass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "features_description",
                    models.TextField(blank=True, verbose_name="Описание характеристик"),
                ),
                (
                    "level_gained",
                    models.IntegerField(
                        default=3,
                        help_text="На каком уровне класса получается этот подкласс",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Уровень получения",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subclasses",
                        to="spells.characterclass",
                        verbose_name="Класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкласс",
                "verbose_name_plural": "Подклассы",
                "unique_together": {("name", "character_class")},
            },
        ),
        migrations.AddField(
            model_name="spell",
            name="aviable_subclasses",
            field=models.ManyToManyField(
                blank=True,
                related_name="aviable_spells",
                to="spells.subclass",
                verbose_name="Подкласс",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="second_subclass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_characters",
                to="spells.subclass",
                verbose_name="Дополнительный подкласс",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="subclass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="spells.subclass",
                verbose_name="Подкласс",
            ),
        ),
        migrations.AddIndex(
            model_name="spell",
            index=models.Index(fields=["level"], name="spells_spel_level_d3ad5e_idx"),
        ),
        migrations.AddIndex(
            model_name="spell",
            index=models.Index(
                fields=["school"], name="spells_spel_school__502d03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spell",
            index=models.Index(
                fields=["attack_type"], name="spells_spel_attack__10b351_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spell",
            index=models.Index(
                fields=["concentration"], name="spells_spel_concent_a6dcd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spell",
            index=models.Index(fields=["ritual"], name="spells_spel_ritual_7adbfb_idx"),
        ),
    ]
