# Generated by Django 6.0 on 2026-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spell",
            name="material_components",
            field=models.ManyToManyField(
                blank=True,
                to="spells.materialcomponent",
                verbose_name="Материальный компонент",
            ),
        ),
    ]
