# Generated by Django 6.0 on 2026-10-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0002_alter_spell_material_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="portrait",
            field=models.ImageField(
                blank=True,
                upload_to="character_portraits/",
                verbose_name="Портрет персонажа",
            ),
        ),
    ]
