# Generated by Django 6.0 on 2026-10-07 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0003_person_portrait"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="portrait_position_x",
            field=models.IntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Положение портрета по горизонтали",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="portrait_position_y",
            field=models.IntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Положение портрета по вертикали",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="portrait_zoom",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Масштаб портрета",
            ),
        ),
    ]
