# Generated by Django 6.0 on 2026-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0004_person_portrait_position_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="saved_spells",
            field=models.ManyToManyField(
                blank=True,
                related_name="saved_by_players",
                to="spells.spell",
                verbose_name="Сохранённые заклинания",
            ),
        ),
    ]
