# Generated by Django 6.0 on 2026-10-08 05:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0005_player_saved_spells"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название умения"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "level",
                    models.IntegerField(
                        help_text="Уровень в этом классе, от 1 до 20.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Уровень получения",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="spells.characterclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "subclass",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оставь пустым для общего умения класса. Укажи подкласс для его специального умения.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="spells.subclass",
                        verbose_name="Подкласс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Умение класса или подкласса",
                "verbose_name_plural": "Умения классов и подклассов",
                "ordering": ["level", "name", "pk"],
            },
        ),
    ]
