# Generated by Django 6.0 on 2026-10-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0006_classfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="classfeature",
            name="levels",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Уровни получения"
            ),
        ),
    ]
