# Generated by Django 6.0 on 2026-10-08 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0007_classfeature_levels"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название раздела"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Разделы с меньшим числом показываются раньше.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="spells.characterclass",
                        verbose_name="Класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел класса",
                "verbose_name_plural": "Разделы классов",
                "ordering": ["position", "pk"],
            },
        ),
    ]
