# Generated by Django 6.0 on 2026-10-08 07:45

import spells.progression
from django.db import migrations, models


def assign_existing_table_types(apps, schema_editor):
    CharacterClass = apps.get_model("spells", "CharacterClass")
    mapping = {
        "варвар": "barbarian", "бард": "bard", "воин": "fighter", "волшебник": "wizard",
        "друид": "druid", "жрец": "cleric", "изобретатель": "artificer", "колдун": "warlock",
        "монах": "monk", "паладин": "paladin", "плут": "rogue", "следопыт": "ranger", "чародей": "sorcerer",
    }
    for item in CharacterClass.objects.using(schema_editor.connection.alias).all():
        table_type = mapping.get(item.name.strip().casefold())
        if table_type and item.progression_table_type == "basic" and not item.progression_columns:
            item.progression_table_type = table_type
            item.save(update_fields=["progression_table_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0008_classsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='progression_columns',
            field=models.JSONField(blank=True, default=list, validators=[spells.progression.validate_class_columns], verbose_name='Столбцы таблицы развития'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='progression_table_type',
            field=models.CharField(choices=[('basic', 'Базовая таблица'), ('barbarian', 'Варвар'), ('bard', 'Бард'), ('fighter', 'Воин'), ('wizard', 'Волшебник'), ('druid', 'Друид'), ('cleric', 'Жрец'), ('artificer', 'Изобретатель'), ('warlock', 'Колдун'), ('monk', 'Монах'), ('paladin', 'Паладин'), ('rogue', 'Плут'), ('ranger', 'Следопыт'), ('sorcerer', 'Чародей'), ('custom', 'Своя таблица')], default='basic', max_length=20, verbose_name='Вид таблицы развития'),
        ),
        migrations.AddField(
            model_name='subclass',
            name='progression_columns',
            field=models.JSONField(blank=True, default=list, validators=[spells.progression.validate_subclass_columns], verbose_name='Дополнительные столбцы подкласса'),
        ),
        migrations.RunPython(assign_existing_table_types, migrations.RunPython.noop),
    ]
