# Generated by Django 6.0 on 2026-10-08 10:07

from django.db import migrations, models


def mark_existing_regular_damage(apps, schema_editor):
    DamageType = apps.get_model("spells", "DamageType")
    DamageType.objects.using(schema_editor.connection.alias).filter(
        is_magic=False,
    ).update(is_regular=True)


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0009_class_progression_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagetype',
            name='is_regular',
            field=models.BooleanField(default=False, verbose_name='Обычный урон'),
        ),
        migrations.RunPython(mark_existing_regular_damage, migrations.RunPython.noop),
    ]
