# Generated by Django 6.0 on 2026-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0010_damagetype_is_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagetype',
            name='image',
            field=models.ImageField(blank=True, upload_to='damage_types/', verbose_name='Картинка'),
        ),
    ]
