# Generated by Django 6.0 on 2026-10-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0011_damagetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='image',
            field=models.ImageField(blank=True, upload_to='effects/', verbose_name='Картинка'),
        ),
    ]
